from django.db import models

LOG_STATUS = (
    ('open', 'Open'),
    ('closed', 'Closed'),
    ('process', 'Process'),
    ('reopen', 'Re-Open'),
)    

class ErrorLog(models.Model):
    level = models.CharField(max_length=200, help_text="Auto generated based on error type, it may be WARNING or ERROR")
    error_msg = models.TextField()
    page = models.CharField(max_length=200)
    ip_address = models.CharField(max_length=200, help_text="Auto generated based on geo")
    user = models.CharField(max_length=200, help_text='The user may be authenticate or anonymous')
    datetime = models.DateTimeField(null=True, blank=True)
    admin_status = models.CharField(max_length=10, default='open', choices=LOG_STATUS, help_text="Admin note of error log.")
    admin_note = models.TextField(null=True, blank=True, help_text="Admin user can add a manual note")
    admin_note_created = models.DateTimeField(auto_now_add=True, null=True, blank=True, help_text="Auto generated by system")
    admin_note_modified = models.DateTimeField(auto_now_add=True, auto_now=True, null=True, blank=True, help_text="Auto generated by system")
